routes/web.php
<?php

use Illuminate\Support\Facades\Route;

Route::get('/', function () {
	return view('welcome');
});

Route::get('/produsen', function() {
	return view('produsen');
});

Auth::routes();

Route::get('/home', 'HomeController@index')->name('home');
Route::get('{id}/produk/{nama_produk}','HomeController@detailproduk')->name('detail.produk');

// ==============================================================
// is super admin
Route::middleware('is_superadmin')->namespace('Superadmin')->prefix('v1/superadmin')->name('superadmin.')->group(function(){
	Route::get('home','HomeController@index')->name('home');
	Route::resource('admin_verifikator','AdminverifikatorController');
});

// is admin distributor
Route::middleware('is_admindistributor')->namespace('Admindistributor')->prefix('admin_dis')->name('admindistributor.')->group(function(){
	Route::get('home','HomeController@index')->name('home');
	Route::resource('product','ProdukController');
	Route::resource('kategories','KategoryController');

	//tambahkan produk
	Route::get('/tambahproduk', function () {
		return view('tampilanproduk');
	});
	//tampilan produk
	Route::get('/tampilanproduk', 'ProdukController@show');
	Route::post('/add_process', 'ProdukController@add_process');
	//menuju web (detail produk dan tambah web)
	Route::get('/detail','ProdukController@index');
});

// is admin verifikator
Route::middleware('is_adminverifikator')->namespace('AdminVerifikator')->prefix('admin_verif')->name('adminverifikator.')->group(function(){
	Route::get('home','HomeController@index')->name('home');
});

Route::get('/kontributor', 'Superadmin\ProdusenController@index')->name('kontributor');
Route::post('/kontributor', 'Superadmin\ProdusenController@input')->name('input.kontributor');

Route::get('/', function () {
    return view('/beranda');
});
//barang
Route::get('/barang', 'BarangController@index');
Route::get('/tambahbarang', 'BarangController@create');
Route::post('/tambahbarang', 'BarangController@store');
Route::get('/edit_barang/{id}', 'BarangController@edit');
Route::post('/edit_barang/{id}', 'BarangController@update');
Route::get('/hapus/{id}', 'BarangController@destroy');

app/Http/Controllers/Admindistributor/HomeController.php
<?php

namespace App\Http\Controllers\Admindistributor;

use App\Http\Controllers\Controller;
use Illuminate\Http\Request;

class HomeController extends Controller
{
	public function __construct()
	{
		$this->middleware('auth');
	}

	public function index()
	{
		return view('admindistributor.home');
	}

	public function create()
	{
		//
	}

	public function store(Request $request)
	{
		//
	}

	public function show($id)
	{
		//
	}

	public function edit($id)
	{
		//
	}

	public function update(Request $request, $id)
	{
		//
	}

	public function destroy($id)
	{
		//
	}
}

app/Http/Controllers/Admindistributor/KategoryController.php
<?php

namespace App\Http\Controllers\Admindistributor;

use App\Http\Controllers\Controller;
use App\Models\Kategory;
use Illuminate\Http\Request;
use Illuminate\Support\Str;
use Illuminate\Validation\Rule;

class KategoryController extends Controller
{
	public function __construct()
	{
		$this->middleware('auth');
	}
	public function index()
	{
		$kategori 	= Kategory::orderby('jenis_kategori','asc')->get();
		return view('admindistributor.kategori.index', compact('kategori'));
	}

	public function create()
	{
		//
	}

	public function store(Request $request)
	{
		$validasikategori 		= $request->validate([
			'jenis_kategori' 	=> 'required|unique:kategories'
		]);
		$kategori = Kategory::create($validasikategori);
		$kategori->url_jenis_kategori = Str::slug($request->jenis_kategori);
		$kategori->save();

		return redirect()->back();
	}

	public function show(Kategory $kategory)
	{
		//
	}

	public function edit($id)
	{
		$kategori = Kategory::find($id);
		return view('admindistributor.kategori.edit', compact('kategori'));
	}

	public function update(Request $request, $id)
	{
		$kategori = Kategory::find($id);
		$request->validate([
			'jenis_kategori' 	=> 'required|unique:kategories',Rule::unique('kategories')->ignore($kategori->id),
		]);
		$kategori->jenis_kategori 		= $request->jenis_kategori;
		$kategori->url_jenis_kategori 	= Str::slug($request->jenis_kategori);
		$kategori->save();

		return redirect()->route('admindistributor.kategories.index');
	}

	public function destroy($id)
	{
		Kategory::find($id)->delete();
		return redirect()->back();
	}
}

app/Http/Controllers/Admindistributor/ProdukController.php
<?php

namespace App\Http\Controllers\Admindistributor;

use App\Http\Controllers\Controller;
use Illuminate\Http\Request;
use App\Models\Product;
use App\Models\Kategory;
use App\Models\QRCode;
use SimpleSoftwareIO\QrCode\Generator;
use Illuminate\Support\Str;

class ProdukController extends Controller
{
	public function __construct()
	{
		$this->middleware('auth');
	}

	public function index(){
		$produk 	= Product::with('kategori','qrcode')->orderby('id','desc')->get();
		// dd($produk);
		$kategori 	= Kategory::orderby('jenis_kategori','asc')->get();
		return view('admindistributor.produk.index', compact('produk','kategori'));
	}

	public function create(){
		return view('admindistributor.produk.create');
	}

	public function store(Request $request){
		$request->validate([
			'nama_produk' 		=> 'required|unique:products',
			'kategori_id'		=> 'required',
			'deskripsi_produk'	=> 'required',
			'foto_produk' 		=> 'required|image|mimes:jpeg,png,jpg,gif,svg|max:2048'
		]);
		$produk 				= Product::create($request->all());
		$produk->url_produk 	= Str::slug($request->nama_produk);
		// change name foto_produk
		$namaFotoProduk 		= time().'.'.$request->foto_produk->extension();
		// move foto to public path foto_produk
		$request->foto_produk->move(public_path('foto_produk'), $namaFotoProduk);
		// save nama foto_produk to db
		$produk->foto_produk 	= $namaFotoProduk;
		$produk->save();

		$produkid 		= $produk->id;
		$qrcodegenerator= new Generator;
		$qr 			= new QRCode;
		$qr->product_id = $produkid;
		$qr->qr_code 	= $qrcodegenerator->encoding('UTF-8')->size(500)->generate(''.route('detail.produk',[$produk->id,$produk->url_produk]).'');
		$qr->save();

		return redirect()->back();
	}

	public function destroy($id){
		$produk = Product::find($id);
		unlink(public_path('foto_produk'.'/'.$produk->foto_produk));
		$produk->delete();
		QRCode::where('product_id',$id)->delete();
		return redirect()->back();
	}
}

resources/views/admindistributor/kategori/edit.blade.php
@extends('layouts.layouts-admin')

@section('content')
<div class="row mt-4">
	<div class="col-lg-12 mb-lg-0 mb-4">
		<div class="card z-index-2 h-100">
			<div class="card-header pb-0 pt-3 bg-transparent">
				<h6 class="text-capitalize">Edit Kategori - {{ $kategori->jenis_kategori }}</h6>
			</div>
			<div class="card-body p-3">
				{{ Form::model($kategori, ['route' => ['admindistributor.kategories.update',$kategori->id]]) }}
					@method('PATCH')
					<div class="form-group">
						<input type="text" name="jenis_kategori" class="form-control @error('jenis_kategori') is-invalid @enderror" placeholder="Jenis Kategori" value="{{ $kategori->jenis_kategori }}">

						@error('jenis_kategori')
							<div class="valid-feedback">{{ $message }}</div>
						@enderror
					</div>

					<div class="form-group">
						<button type="submit" class="btn btn-primary w-100 mb-3">Simpan</button>
					</div>
				{{ Form::close() }}
			</div>
		</div>
	</div>
</div>
@endsection

@push('styles')
@endpush

@push('scripts')
@endpush

resources/views/admindistributor/kategori/index.blade.php
@extends('layouts.layouts-admin')

@section('content')
<div class="row mt-4">
	<div class="col-lg-12 mb-lg-0 mb-4">
		<div class="card z-index-2 h-100">
			<div class="card-header pb-0 pt-3 bg-transparent">
				<h6 class="text-capitalize">Kategori</h6>
			</div>
			<div class="card-body p-3">
				{{ Form::open(['route'=>'admindistributor.kategories.store','method'=>'POST']) }}
					<div class="form-group">
						<input type="text" name="jenis_kategori" class="form-control @error('jenis_kategori') is-invalid @enderror" placeholder="Jenis Kategori">

						@error('jenis_kategori')
							<div class="valid-feedback">{{ $message }}</div>
						@enderror
					</div>

					<div class="form-group">
						<button type="submit" class="btn btn-primary btn-sm w-100 mb-3">Tambah Kategori</button>
					</div>
				{{ Form::close() }}
			</div>
		</div>
	</div>
</div>
<div class="row mt-4">
	<div class="col-lg-12 mb-lg-0 mb-4">
		<div class="card z-index-2 h-100">
			<div class="card-body p-3">
				<table id="idkategoriadd" class="table table-striped table-bordered" style="width:100%">
					<thead>
						<tr>
							<th>No.</th>
							<th>Kategori</th>
							<th>Tanggal Pembuatan/Perubahan</th>
							<th></th>
						</tr>
					</thead>
					<tbody>
						@foreach($kategori as $kategori)
						<tr>
							<td>{{ $loop->iteration }}</td>
							<td>{{ $kategori->jenis_kategori }}</td>
							<td>{{ $kategori->updated_at }}</td>
							<td>
								{{ Form::model($kategori, ['route'=>['admindistributor.kategories.destroy',$kategori->id]]) }}
									{{-- edit --}}
									<a href="{{ route('admindistributor.kategories.edit',$kategori->id) }}" class="btn btn-warning"><i class="fa-solid fa-pen-to-square"></i></a>

									{{-- hapus --}}
									@method('DELETE')
									<button type="submit" class="btn btn-danger" onclick="return confirm('Yakin mau hapus kategori, {{ $kategori->jenis_kategori }} ?')"><i class="fa-solid fa-trash-can"></i></button>
								{{ Form::close() }}
							</td>
						</tr>
						@endforeach
					</tbody>
					<tfoot>
						<tr>
							<th>No.</th>
							<th>Kategori</th>
							<th>Tanggal Pembuatan/Perubahan</th>
							<th></th>
						</tr>
					</tfoot>
				</table>
			</div>
		</div>
	</div>
</div>
@endsection

@push('styles')
	<link rel="stylesheet" href="https://cdn.datatables.net/1.11.5/css/dataTables.bootstrap5.min.css" integrity="sha512-160haaGB7fVnCfk/LJAEsACLe6gMQMNCM3Le1vF867rwJa2hcIOgx34Q1ah10RWeLVzpVFokcSmcint/lFUZlg==" crossorigin="anonymous">
@endpush

@push('scripts')
	<script src="https://ajax.googleapis.com/ajax/libs/jquery/3.6.0/jquery.min.js" integrity="sha512-894YE6QWD5I59HgZOGReFYm4dnWc1Qt5NtvYSaNcOP+u1T9qYdvdihz0PPSiiqn/+/3e7Jo4EaG7TubfWGUrMQ==" crossorigin="anonymous"></script>
	<script src="https://cdn.datatables.net/1.11.5/js/jquery.dataTables.min.js" integrity="sha512-gzsDzZKwY3mJWOtC5MviMWjvGPL+FdPaxN62NTXdu0hiogj9QnpY8gpu6QGk9RExu13mOvFpHbkLfB0E31jwOQ==" crossorigin="anonymous"></script>
	<script src="https://cdn.datatables.net/1.11.5/js/dataTables.bootstrap5.min.js" integrity="sha512-nfoMMJ2SPcUdaoGdaRVA1XZpBVyDGhKQ/DCedW2k93MTRphPVXgaDoYV1M/AJQLCiw/cl2Nbf9pbISGqIEQRmQ==" crossorigin="anonymous"></script>
	<script src="https://cdn.ckeditor.com/4.18.0/standard/ckeditor.js" integrity="sha512-l6Ui9CEOeis2DifjL9V8tcB76kEhvlXmpZrKgFvgN4zY3AeZL/qNlJNHFtDTqTkyYg2uGgh5cyMaQ5oMSZiXGw==" crossorigin="anonymous"></script>
<script>
	$(document).ready(function ($) {
		$.noConflict();
		$('#idkategoriadd').DataTable();
	} );
</script>
@endpush