routes/web.php
<?php

use Illuminate\Support\Facades\Route;

Route::get('/', function () {
	return view('welcome');
});

Route::get('/produsen', function() {
	return view('produsen');
});

Auth::routes();

Route::get('/home', 'HomeController@index')->name('home');
Route::get('{id}/produk/{nama_produk}','HomeController@detailproduk')->name('detail.produk');

// ==============================================================
// is super admin
Route::middleware('is_superadmin')->namespace('Superadmin')->prefix('v1/superadmin')->name('superadmin.')->group(function(){
	Route::get('home','HomeController@index')->name('home');
	Route::resource('admin_verifikator','AdminverifikatorController');
});

// is admin distributor
Route::middleware('is_admindistributor')->namespace('Admindistributor')->prefix('admin_dis')->name('admindistributor.')->group(function(){
	Route::get('home','HomeController@index')->name('home');
	Route::resource('product','ProdukController');
	Route::resource('kategories','KategoryController');

	//tambahkan produk
	Route::get('/tambahproduk', function () {
		return view('tampilanproduk');
	});
	//tampilan produk
	Route::get('/tampilanproduk', 'ProdukController@show');
	Route::post('/add_process', 'ProdukController@add_process');
	//menuju web (detail produk dan tambah web)
	Route::get('/detail','ProdukController@index');
});

// is admin verifikator
Route::middleware('is_adminverifikator')->namespace('AdminVerifikator')->prefix('admin_verif')->name('adminverifikator.')->group(function(){
	Route::get('home','HomeController@index')->name('home');
});

Route::get('/kontributor', 'Superadmin\ProdusenController@index')->name('kontributor');
Route::post('/kontributor', 'Superadmin\ProdusenController@input')->name('input.kontributor');

Route::get('/', function () {
    return view('/beranda');
});
//barang
Route::get('/barang', 'BarangController@index');
Route::get('/tambahbarang', 'BarangController@create');
Route::post('/tambahbarang', 'BarangController@store');
Route::get('/edit_barang/{id}', 'BarangController@edit');
Route::post('/edit_barang/{id}', 'BarangController@update');
Route::get('/hapus/{id}', 'BarangController@destroy');

resources/views/layouts/app.blade.php
<!doctype html>
<html lang="{{ str_replace('_', '-', app()->getLocale()) }}">
<head>
	<meta charset="utf-8">
	<meta name="viewport" content="width=device-width, initial-scale=1">
	<meta name="csrf-token" content="{{ csrf_token() }}">
	<title>{{ config('app.name', 'Laravel') }}</title>
	<link rel="dns-prefetch" href="//fonts.gstatic.com">
	<link href="https://fonts.googleapis.com/css?family=Nunito" rel="stylesheet">
	<link href="{{ asset('css/app.css') }}" rel="stylesheet">
	<link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/6.0.0/css/all.min.css">
	@stack('styles')
</head>
<body>
	<div id="app">
		<nav class="navbar navbar-expand-md navbar-light bg-white shadow-sm">
			<div class="container">
				<a class="navbar-brand" href="{{ url('/') }}">
					{{ config('app.name', 'Laravel') }}
				</a>
				<button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="{{ __('Toggle navigation') }}">
					<span class="navbar-toggler-icon"></span>
				</button>

				<div class="collapse navbar-collapse" id="navbarSupportedContent">
					<!-- Left Side Of Navbar -->
					<ul class="navbar-nav mr-auto">
						@guest
						@else
						@if(auth()->user()->is_superadmin == 1)
							<li class="nav-item">
								<a class="nav-link" href="{{ route('superadmin.admin_verifikator.index') }}">Admin Verifikator</a>
							</li>
						@elseif(auth()->user()->is_adminverifikator == 1)
							<li class="nav-item">
								<a class="nav-link" href="#">coba admin distributor</a>
							</li>
						@elseif(auth()->user()->is_admindistributor == 1)
							<li class="nav-item dropdown">
								<a id="navbarDropdown_produk" class="nav-link dropdown-toggle" href="#" role="button" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false" v-pre>
									Produk
								</a>

								<div class="dropdown-menu dropdown-menu-right" aria-labelledby="navbarDropdown_produk">
									<a class="dropdown-item" href="{{ route('admindistributor.product.index') }}">
										Produk
									</a>
									<a class="dropdown-item" href="{{ route('admindistributor.kategories.index') }}">
										Kategori
									</a>
								</div>
							</li>
						@endif
						@endguest
					</ul>

					<!-- Right Side Of Navbar -->
					<ul class="navbar-nav ml-auto">
						<!-- Authentication Links -->
						@guest
							<li class="nav-item">
								<a class="nav-link" href="{{ route('login') }}">{{ __('Login') }}</a>
							</li>
							@if (Route::has('register'))
								<li class="nav-item">
									<a class="nav-link" href="{{ route('register') }}">{{ __('Register') }}</a>
								</li>
							@endif
						@else
							<li class="nav-item dropdown">
								<a id="navbarDropdown" class="nav-link dropdown-toggle" href="#" role="button" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false" v-pre>
									{{ Auth::user()->name }}
								</a>

								<div class="dropdown-menu dropdown-menu-right" aria-labelledby="navbarDropdown">
									<a class="dropdown-item" href="{{ route('logout') }}"
									   onclick="event.preventDefault();
													 document.getElementById('logout-form').submit();">
										{{ __('Logout') }}
									</a>

									<form id="logout-form" action="{{ route('logout') }}" method="POST" class="d-none">
										@csrf
									</form>
								</div>
							</li>
						@endguest
					</ul>
				</div>
			</div>
		</nav>

		<main class="py-4">
			@yield('content')
		</main>
	</div>

	<script src="{{ asset('js/app.js') }}" defer></script>
	@stack('scripts')
</body>
</html>

resources/views/layouts/layouts-admin.blade.php
<!DOCTYPE html>
<html lang="en">
<head>
	<meta charset="utf-8" />
	<meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">
	<link rel="apple-touch-icon" sizes="76x76" href="{{ asset('5mhuwAcA/img/favicon.png') }}?v=2.0.1">
	<link rel="icon" type="image/png" href="{{ asset('5mhuwAcA/img/favicon.png') }}?v=2.0.1">
	<title> {{ config('app.name', 'Omah Produk') }} </title>
	
	<link href="https://fonts.googleapis.com/css?family=Open+Sans:300,400,600,700" rel="stylesheet" />
	
	<script src="https://kit.fontawesome.com/42d5adcbca.js" integrity="sha512-LnuABhhXE0X/lbkFBPRXkBOpw4tSvtFgtMWoKOr7dq5Uub+gSHX+UEO2S6Jw5KRYGCrjVUe5d7OLg8VefUFFTQ==" crossorigin="anonymous"></script>
	
	<link id="pagestyle" href="{{ asset('5mhuwAcA/css/app-back.css') }}?v=2.0.1" rel="stylesheet" />
	
	<link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/6.0.0/css/all.min.css" integrity="sha512-9usAa10IRO0HhonpyAIVpjrylPvoDwiPUiKdWk5t3PyolY1cOd4DSE0Ga+ri4AuTroPR5aQvXU9xC6qOPnzFeg==" crossorigin="anonymous">

	@stack('styles')

</head>

<body class="g-sidenav-show bg-gray-100">
	<div class="min-height-300 bg-primary position-absolute w-100"></div>

	@include('layouts.components.aside')
	
	<main class="main-content position-relative border-radius-lg ">
		
		@include('layouts.components.nav')
		
		<div class="container-fluid py-4">
			@yield('content')
			@include('layouts.components.footer')
		</div>
	</main>

	<script src="https://cdnjs.cloudflare.com/ajax/libs/popper.js/2.10.2/umd/popper.min.js?v=2.10.2" integrity="sha512-nnzkI2u2Dy6HMnzMIkh7CPd1KX445z38XIu4jG1jGw7x5tSL3VBjE44dY4ihMU1ijAQV930SPM12cCFrB18sVw==" crossorigin="anonymous"></script>
	<script src="https://cdnjs.cloudflare.com/ajax/libs/bootstrap/5.1.3/js/bootstrap.min.js?v=2.0.1" integrity="sha512-OvBgP9A2JBgiRad/mM36mkzXSXaJE9BEIENnVEmeZdITvwT09xnxLtT4twkCa8m/loMbPHsvPl0T8lRGVBwjlQ==" crossorigin="anonymous"></script>

	<script src="{{ asset('5mhuwAcA/js/perfect-scrollbar.js') }}?v=2.0.1"></script>
	<script src="{{ asset('5mhuwAcA/js/smooth-scrollbar.js') }}?v=2.0.1"></script>
	<script src="{{ asset('5mhuwAcA/js/chartjs.js') }}?v=2.0.1"></script>

	<script>
		var win = navigator.platform.indexOf('Win') > -1;
		if (win && document.querySelector('#sidenav-scrollbar')) {
			var options = {
				damping: '0.5'
			}
			Scrollbar.init(document.querySelector('#sidenav-scrollbar'), options);
		}
	</script>

	<script async defer src="{{ asset('5mhuwAcA/js/app-back.js') }}?v=2.0.1"></script>
	@stack('scripts')
</body>
</html>