routes/web.php
<?php

use Illuminate\Support\Facades\Route;

Route::get('/', function () {
	return view('welcome');
});

Route::get('/produsen', function() {
	return view('produsen');
});

Auth::routes();

Route::get('/home', 'HomeController@index')->name('home');
Route::get('{id}/produk/{nama_produk}','HomeController@detailproduk')->name('detail.produk');

// ==============================================================
// is super admin
Route::middleware('is_superadmin')->namespace('Superadmin')->prefix('v1/superadmin')->name('superadmin.')->group(function(){
	Route::get('home','HomeController@index')->name('home');
	Route::resource('admin_verifikator','AdminverifikatorController');
});

// is admin distributor
Route::middleware('is_admindistributor')->namespace('Admindistributor')->prefix('admin_dis')->name('admindistributor.')->group(function(){
	Route::get('home','HomeController@index')->name('home');
	Route::resource('product','ProdukController');
	Route::resource('kategories','KategoryController');

	//tambahkan produk
	Route::get('/tambahproduk', function () {
		return view('tampilanproduk');
	});
	//tampilan produk
	Route::get('/tampilanproduk', 'ProdukController@show');
	Route::post('/add_process', 'ProdukController@add_process');
	//menuju web (detail produk dan tambah web)
	Route::get('/detail','ProdukController@index');
});

// is admin verifikator
Route::middleware('is_adminverifikator')->namespace('AdminVerifikator')->prefix('admin_verif')->name('adminverifikator.')->group(function(){
	Route::get('home','HomeController@index')->name('home');
});

Route::get('/kontributor', 'Superadmin\ProdusenController@index')->name('kontributor');
Route::post('/kontributor', 'Superadmin\ProdusenController@input')->name('input.kontributor');

Route::get('/', function () {
    return view('/beranda');
});
//barang
Route::get('/barang', 'BarangController@index');
Route::get('/tambahbarang', 'BarangController@create');
Route::post('/tambahbarang', 'BarangController@store');
Route::get('/edit_barang/{id}', 'BarangController@edit');
Route::post('/edit_barang/{id}', 'BarangController@update');
Route::get('/hapus/{id}', 'BarangController@destroy');

app/Http/Controllers/Superadmin/AdminverifikatorController.php
<?php

namespace App\Http\Controllers\Superadmin;

use App\Http\Controllers\Controller;
use Illuminate\Http\Request;
use App\User;
use Carbon\Carbon;

class AdminverifikatorController extends Controller
{
	public function index()
	{
		$user = User::where('is_adminverifikator',1)->get();
		return view('superadmin.verifikator.index', compact('user'));
	}

	public function store(Request $request)
	{
		$val = $request->validate([
			'name' 		=> 'required', 'string', 'max:255',
            'email' 	=> 'required', 'string', 'email', 'max:255', 'unique:users',
            'password' 	=> 'required', 'string', 'min:8', 'confirmed',
		]);
		
		$user = User::create($val);
		$user->is_adminverifikator = '1';
		$user->password = bcrypt($request->password);
		$user->email_verified_at = Carbon::now();
		$user->save();

		return redirect()->back();
	}

	public function show($id)
	{
		//
	}

	public function edit($id)
	{
		$user = User::find($id);
		return view('superadmin.verifikator.edit', compact('user'));
	}

	public function update(Request $request, $id)
	{
		$user = User::find($id);
		$user->name = $request->name;
		if(is_null($request->password)){
			// 
		}else{
			$user->password = bcrypt($request->password);
		}
		$user->save();
		return redirect()->route('superadmin.admin_verifikator.index');
	}

	public function destroy($id)
	{
		$user = User::find($id)->delete();
		return redirect()->back();

	}
}

app/Http/Controllers/Superadmin/HomeController.php
<?php

namespace App\Http\Controllers\Superadmin;

use App\Http\Controllers\Controller;
use Illuminate\Http\Request;

class HomeController extends Controller
{
	public function __construct()
	{
		$this->middleware('auth');
	}

	public function index()
	{
		return view('superadmin.home');
	}
}

app/Http/Controllers/Superadmin/ProdusenController.php
<?php

namespace App\Http\Controllers\Superadmin;

use App\Http\Controllers\Controller;
use Illuminate\Http\Request;
use App\Model\tambahprodusen;
use App\Model\Detailtambahprodusen;

class ProdusenController extends Controller
{
    public function index()
    {
        return view('superadmin.kontributor.index');
    }

    public function input(Request $request)
    {
        $data = $request->all();
        // dd($data);
        $produsen = new tambahprodusen;
        $produsen->name = $data ['name'];
        $produsen->email = $data ['email'];
        $produsen->save();

        $detailprodusen = new Detailtambahprodusen;
        $detailprodusen->user_id = $produsen->id;
        $detailprodusen->address = $data['address'];
        $detailprodusen->phone = $data['phone'];
        $detailprodusen->kode_pos = $data['kode_pos'];
        $detailprodusen->save();



        return redirect()->back()->with('status', 'Data Berhasil di Input');
    }

}

resources/views/superadmin/verifikator/edit.blade.php
@extends('layouts.layouts-admin')

@section('content')
<div class="row mt-4">
	<div class="col-lg-12 mb-lg-0 mb-4">
		<div class="card z-index-2 h-100">
			<div class="card-header pb-0 pt-3 bg-transparent">
				<h6 class="text-capitalize">Edit Admin Verifikator - {{ $user->name }}</h6>
			</div>
			<div class="card-body p-3">
				{{ Form::model($user, ['route' => ['superadmin.admin_verifikator.update',$user->id]]) }}
					@method('PATCH')
					<div class="form-group">
						<input type="text" name="name" class="form-control @error('name') is-invalid @enderror" placeholder="Nama" value="{{ $user->name }}">

						@error('name')
							<div class="valid-feedback">{{ $message }}</div>
						@enderror
					</div>
					<div class="form-group">
						<input type="email" name="email" class="form-control @error('email') is-invalid @enderror" placeholder="Email" value="{{ $user->email }}" readonly>

						@error('email')
							<div class="valid-feedback">{{ $message }}</div>
						@enderror
					</div>
					<div class="form-group">
						<input type="password" name="password" class="form-control @error('password') is-invalid @enderror" placeholder="Password">

						@error('password')
							<div class="valid-feedback">{{ $message }}</div>
						@enderror
					</div>

					<div class="form-group">
						<button type="submit" class="btn btn-primary w-100 mb-3">Simpan</button>
					</div>
				{{ Form::close() }}
			</div>
		</div>
	</div>
</div>
@endsection

@push('styles')
@endpush

@push('scripts')
@endpush

resources/views/superadmin/verifikator/index.blade.php
@extends('layouts.layouts-admin')

@section('content')
<div class="row mt-4">
	<div class="col-lg-12 mb-lg-0 mb-4">
		<div class="card z-index-2 h-100">
			<div class="card-header pb-0 pt-3 bg-transparent">
				<h6 class="text-capitalize">Admin Verifikator</h6>
			</div>
			<div class="card-body p-3">
				{{ Form::open(['route'=>'superadmin.admin_verifikator.store','method'=>'POST','files'=>true]) }}
					<div class="form-group">
						<input type="text" name="name" class="form-control @error('name') is-invalid @enderror" placeholder="Nama">

						@error('name')
							<div class="valid-feedback">{{ $message }}</div>
						@enderror
					</div>
					<div class="form-group">
						<input type="email" name="email" class="form-control @error('email') is-invalid @enderror" placeholder="Email">

						@error('email')
							<div class="valid-feedback">{{ $message }}</div>
						@enderror
					</div>
					<div class="form-group">
						<input type="password" name="password" class="form-control @error('password') is-invalid @enderror" placeholder="Password">

						@error('password')
							<div class="valid-feedback">{{ $message }}</div>
						@enderror
					</div>

					<div class="form-group">
						<button type="submit" class="btn btn-primary btn-sm w-100 mb-3">Tambah Admin Verifikator</button>
					</div>
				{{ Form::close() }}
			</div>
		</div>
	</div>
</div>
<div class="row mt-4">
	<div class="col-lg-12 mb-lg-0 mb-4">
		<div class="card z-index-2 h-100">
			<div class="card-body p-3">
				<table id="idsuperadminaddverifikator" class="table table-striped table-bordered" style="width:100%">
					<thead>
						<tr>
							<th>No.</th>
							<th>Name</th>
							<th>Email</th>
							<th>Verified at</th>
							<th></th>
						</tr>
					</thead>
					<tbody>
						@foreach($user as $user)
						<tr>
							<td>{{ $loop->iteration }}</td>
							<td>{{ $user->name }}</td>
							<td>{{ $user->email }}</td>
							<td>{{ $user->email_verified_at }}</td>
							<td>
								{{ Form::model($user, ['route'=>['superadmin.admin_verifikator.destroy',$user->id]]) }}
									<a href="{{ route('superadmin.admin_verifikator.edit',$user->id) }}" class="btn btn-warning"><i class="fa-solid fa-pen-to-square"></i></a>
									@method('DELETE')
									<button type="submit" class="btn btn-danger" onclick="return confirm('Yakin mau hapus user, {{ $user->name }} ?')"><i class="fa-solid fa-trash-can"></i></button>
								{{ Form::close() }}
							</td>
						</tr>
						@endforeach
					</tbody>
					<tfoot>
						<tr>
							<th>No.</th>
							<th>Name</th>
							<th>Email</th>
							<th>Verified at</th>
							<th></th>
						</tr>
					</tfoot>
				</table>
			</div>
		</div>
	</div>
</div>
@endsection

@push('styles')
	<link rel="stylesheet" href="https://cdn.datatables.net/1.11.5/css/dataTables.bootstrap5.min.css" integrity="sha512-160haaGB7fVnCfk/LJAEsACLe6gMQMNCM3Le1vF867rwJa2hcIOgx34Q1ah10RWeLVzpVFokcSmcint/lFUZlg==" crossorigin="anonymous">
@endpush

@push('scripts')
	<script src="https://ajax.googleapis.com/ajax/libs/jquery/3.6.0/jquery.min.js" integrity="sha512-894YE6QWD5I59HgZOGReFYm4dnWc1Qt5NtvYSaNcOP+u1T9qYdvdihz0PPSiiqn/+/3e7Jo4EaG7TubfWGUrMQ==" crossorigin="anonymous"></script>
	<script src="https://cdn.datatables.net/1.11.5/js/jquery.dataTables.min.js" integrity="sha512-gzsDzZKwY3mJWOtC5MviMWjvGPL+FdPaxN62NTXdu0hiogj9QnpY8gpu6QGk9RExu13mOvFpHbkLfB0E31jwOQ==" crossorigin="anonymous"></script>
	<script src="https://cdn.datatables.net/1.11.5/js/dataTables.bootstrap5.min.js" integrity="sha512-nfoMMJ2SPcUdaoGdaRVA1XZpBVyDGhKQ/DCedW2k93MTRphPVXgaDoYV1M/AJQLCiw/cl2Nbf9pbISGqIEQRmQ==" crossorigin="anonymous"></script>
<script>
	$(document).ready(function ($) {
		$.noConflict();
		$('#idsuperadminaddverifikator').DataTable();
	} );
</script>
@endpush